"""add users uploads categories chat_history budgets

Revision ID: 2dd3d0bd5824
Revises: 2e17decadab7
Create Date: 2026-03-31 20:04:39.405586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd3d0bd5824'
down_revision: Union[str, Sequence[str], None] = '2e17decadab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
